-- Generated from appConstants.js

create table if not exists public.class_spell_rules (
  id bigint generated always as identity primary key,
  class_name text not null,
  spell_id bigint not null references public.spells(id) on delete cascade,
  spell_level int not null check (spell_level between 1 and 6),
  cost int not null default 0,
  max_count int,
  frequency jsonb,
  restricted boolean not null default false,
  source_type text not null,
  option_group text,
  is_look_the_part boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists idx_class_spell_rules_class_level on public.class_spell_rules(class_name, spell_level);
create index if not exists idx_class_spell_rules_spell_id on public.class_spell_rules(spell_id);
create unique index if not exists idx_class_spell_rules_unique_key
  on public.class_spell_rules(class_name, spell_id, spell_level, source_type, coalesce(option_group, ''), is_look_the_part);

alter table public.class_spell_rules enable row level security;
drop policy if exists "Anyone can read class spell rules" on public.class_spell_rules;
create policy "Anyone can read class spell rules"
  on public.class_spell_rules
  for select
  to anon, authenticated
  using (true);

insert into public.class_spell_rules
  (class_name, spell_id, spell_level, cost, max_count, frequency, restricted, source_type, option_group, is_look_the_part)
values
  ('Bard', 33, 1, 1, null, '{"amount":1,"per":"Refresh","charge":"Charge x5"}'::jsonb, false, 'level_spell', null, false),
  ('Bard', 52, 1, 2, 2, null, false, 'level_spell', null, false),
  ('Bard', 56, 1, 2, 2, null, false, 'level_spell', null, false),
  ('Bard', 88, 1, 1, null, '{"amount":1,"per":"Life","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Bard', 124, 1, 1, null, '{"amount":1,"per":"Life","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Bard', 134, 1, 1, null, '{"amount":1,"per":"Life","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Bard', 142, 1, 1, 1, '{"amount":null,"per":null,"charge":"Unlimited"}'::jsonb, false, 'level_spell', null, false),
  ('Bard', 46, 2, 1, null, '{"amount":2,"per":"Refresh","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Bard', 49, 2, 3, 1, null, false, 'level_spell', null, false),
  ('Bard', 76, 2, 1, null, '{"amount":1,"per":"Refresh","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Bard', 86, 2, 1, 4, '{"amount":1,"per":"Refresh","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Bard', 98, 2, 1, null, '{"amount":1,"per":"Life","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Bard', 140, 2, 1, 1, '{"amount":null,"per":null,"charge":"Unlimited"}'::jsonb, false, 'level_spell', null, false),
  ('Bard', 147, 2, 1, 1, '{"amount":null,"per":null,"charge":"Unlimited"}'::jsonb, false, 'level_spell', null, false),
  ('Bard', 20, 3, 1, null, '{"amount":1,"per":"Life","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Bard', 15, 3, 1, 1, '{"amount":1,"per":"Refresh","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Bard', 31, 3, 1, 4, '{"amount":1,"per":"Life","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Bard', 58, 3, 1, 2, '{"amount":1,"per":"Life","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Bard', 51, 3, 2, 1, null, false, 'level_spell', null, false),
  ('Bard', 143, 3, 1, 1, '{"amount":null,"per":null,"charge":"Unlimited"}'::jsonb, false, 'level_spell', null, false),
  ('Bard', 5, 4, 1, 4, '{"amount":1,"per":"Refresh","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Bard', 175, 4, 3, 1, null, false, 'level_spell', null, false),
  ('Bard', 126, 4, 1, null, '{"amount":1,"per":"Refresh","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Bard', 136, 4, 1, null, '{"amount":1,"per":"Refresh","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Bard', 141, 4, 1, 1, '{"amount":null,"per":null,"charge":"Unlimited"}'::jsonb, false, 'level_spell', null, false),
  ('Bard', 145, 4, 1, 1, '{"amount":null,"per":null,"charge":"Unlimited"}'::jsonb, false, 'level_spell', null, false),
  ('Bard', 156, 4, 1, null, '{"amount":1,"per":"Refresh","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Bard', 159, 4, 1, 2, '{"amount":1,"per":"Life","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Bard', 161, 4, 1, null, '{"amount":1,"per":"Refresh","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Bard', 8, 5, 1, null, '{"amount":1,"per":"Refresh","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Bard', 6, 5, 1, 2, '{"amount":1,"per":"Life","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Bard', 42, 5, 1, 1, '{"amount":1,"per":"Refresh","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Bard', 50, 5, 3, 1, null, false, 'level_spell', null, false),
  ('Bard', 77, 5, 1, null, '{"amount":1,"per":"Refresh","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Bard', 93, 5, 1, null, '{"amount":1,"per":"Life","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Bard', 146, 5, 1, 1, '{"amount":null,"per":null,"charge":"Unlimited"}'::jsonb, false, 'level_spell', null, false),
  ('Bard', 29, 6, 2, 1, null, false, 'level_spell', null, false),
  ('Bard', 40, 6, 2, 1, null, false, 'level_spell', null, false),
  ('Bard', 186, 6, 2, 1, null, false, 'level_spell', null, false),
  ('Bard', 91, 6, 1, 1, null, false, 'level_spell', null, false),
  ('Bard', 135, 6, 1, null, '{"amount":1,"per":"Refresh","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Bard', 144, 6, 1, 1, '{"amount":1,"per":"Refresh","charge":"Charge x5"}'::jsonb, false, 'level_spell', null, false),
  ('Bard', 148, 6, 1, null, '{"amount":1,"per":"Refresh","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Healer', 13, 1, 1, null, '{"amount":1,"per":"Life","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Healer', 26, 1, 1, null, '{"amount":1,"per":"Life","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Healer', 51, 1, 2, 1, null, false, 'level_spell', null, false),
  ('Healer', 52, 1, 3, 2, null, false, 'level_spell', null, false),
  ('Healer', 56, 1, 2, 2, null, false, 'level_spell', null, false),
  ('Healer', 74, 1, 1, null, '{"amount":1,"per":"Refresh","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Healer', 75, 1, 1, 1, '{"amount":null,"per":null,"charge":"Unlimited"}'::jsonb, false, 'level_spell', null, false),
  ('Healer', 124, 1, 1, null, '{"amount":2,"per":"Life","charge":"Charge x3"}'::jsonb, false, 'level_spell', null, false),
  ('Healer', 2, 2, 1, null, '{"amount":1,"per":"Life","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Healer', 48, 2, 1, 4, '{"amount":2,"per":"Balls","charge":"Unlimited"}'::jsonb, false, 'level_spell', null, false),
  ('Healer', 176, 2, 3, 1, null, false, 'level_spell', null, false),
  ('Healer', 76, 2, 1, null, '{"amount":1,"per":"Refresh","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Healer', 79, 2, 1, null, '{"amount":1,"per":"Life","charge":"Charge x3"}'::jsonb, false, 'level_spell', null, false),
  ('Healer', 86, 2, 2, 2, '{"amount":1,"per":"Life","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Healer', 130, 2, 1, null, '{"amount":1,"per":"Life","charge":"Charge x3"}'::jsonb, false, 'level_spell', null, false),
  ('Healer', 134, 2, 1, null, '{"amount":1,"per":"Life","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Healer', 154, 2, 1, null, '{"amount":1,"per":"Life","charge":"Charge x3"}'::jsonb, false, 'level_spell', null, false),
  ('Healer', 3, 3, 1, null, '{"amount":1,"per":"Refresh","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Healer', 12, 3, 1, null, '{"amount":1,"per":"Life","charge":"Charge x3"}'::jsonb, false, 'level_spell', null, false),
  ('Healer', 50, 3, 2, 1, null, false, 'level_spell', null, false),
  ('Healer', 58, 3, 1, 2, '{"amount":1,"per":"Life","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Healer', 69, 3, 1, null, '{"amount":1,"per":"Refresh","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Healer', 82, 3, 1, 3, '{"amount":1,"per":"Ball","charge":"Unlimited"}'::jsonb, false, 'level_spell', null, false),
  ('Healer', 98, 3, 1, null, '{"amount":1,"per":"Life","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Healer', 120, 3, 1, null, '{"amount":1,"per":"Life","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Healer', 127, 3, 1, null, '{"amount":1,"per":"Refresh","charge":"Charge x5"}'::jsonb, false, 'level_spell', null, false),
  ('Healer', 25, 4, 1, null, '{"amount":1,"per":"Refresh","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Healer', 28, 4, 1, 1, '{"amount":1,"per":"Refresh","charge":"Charge x10"}'::jsonb, false, 'level_spell', null, false),
  ('Healer', 43, 4, 1, null, '{"amount":1,"per":"Refresh","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Healer', 70, 4, 1, null, '{"amount":1,"per":"Life","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Healer', 81, 4, 1, 2, '{"amount":2,"per":"Refresh","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Healer', 119, 4, 1, null, '{"amount":1,"per":"Refresh","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Healer', 159, 4, 1, 2, '{"amount":1,"per":"Life","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Healer', 160, 4, 1, 2, '{"amount":1,"per":"Life","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Healer', 1, 5, 1, 2, '{"amount":1,"per":"Ball","charge":"Unlimited"}'::jsonb, false, 'level_spell', null, false),
  ('Healer', 6, 5, 1, null, '{"amount":1,"per":"Refresh","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Healer', 23, 5, 1, null, '{"amount":1,"per":"Refresh","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Healer', 47, 5, 1, null, '{"amount":1,"per":"Refresh","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Healer', 72, 5, 1, null, '{"amount":1,"per":"Refresh","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Healer', 151, 5, 1, 2, '{"amount":1,"per":"Life","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Healer', 167, 5, 2, null, '{"amount":1,"per":"Refresh","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Healer', 7, 6, 1, null, '{"amount":1,"per":"Refresh","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Healer', 96, 6, 1, 1, '{"amount":1,"per":"Refresh","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Healer', 104, 6, 1, 1, null, false, 'level_spell', null, false),
  ('Healer', 105, 6, 1, null, '{"amount":1,"per":"Life","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Healer', 108, 6, 1, null, '{"amount":1,"per":"Refresh","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Healer', 114, 6, 1, 1, null, false, 'level_spell', null, false),
  ('Healer', 118, 6, 1, null, '{"amount":1,"per":"Refresh","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Healer', 148, 6, 1, 4, '{"amount":1,"per":"Refresh","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Healer', 171, 6, 2, 1, null, false, 'level_spell', null, false),
  ('Wizard', 13, 1, 1, null, '{"amount":1,"per":"Life","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Wizard', 52, 1, 2, 1, null, false, 'level_spell', null, false),
  ('Wizard', 56, 1, 2, 2, null, false, 'level_spell', null, false),
  ('Wizard', 66, 1, 1, null, '{"amount":1,"per":"Life","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Wizard', 61, 1, 1, 8, '{"amount":3,"per":"Balls","charge":"Unlimited"}'::jsonb, false, 'level_spell', null, false),
  ('Wizard', 78, 1, 1, null, '{"amount":1,"per":"Life","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Wizard', 98, 1, 1, null, '{"amount":1,"per":"Life","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Wizard', 134, 1, 1, null, '{"amount":1,"per":"Life","charge":"Charge x3"}'::jsonb, false, 'level_spell', null, false),
  ('Wizard', 12, 2, 1, null, '{"amount":1,"per":"Life","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Wizard', 31, 2, 1, null, '{"amount":1,"per":"Life","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Wizard', 48, 2, 1, 3, '{"amount":2,"per":"Balls","charge":"Unlimited"}'::jsonb, false, 'level_spell', null, false),
  ('Wizard', 86, 2, 1, null, '{"amount":1,"per":"Refresh","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Wizard', 110, 2, 1, null, '{"amount":1,"per":"Refresh","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Wizard', 124, 2, 1, null, '{"amount":1,"per":"Life","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Wizard', 158, 2, 1, 3, '{"amount":1,"per":"Ball","charge":"Unlimited"}'::jsonb, false, 'level_spell', null, false),
  ('Wizard', 160, 2, 1, 2, '{"amount":1,"per":"Life","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Wizard', 43, 3, 1, null, '{"amount":1,"per":"Refresh","charge":"Charge x3"}'::jsonb, false, 'level_spell', null, false),
  ('Wizard', 44, 3, 1, null, '{"amount":1,"per":"Refresh","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Wizard', 58, 3, 1, 2, '{"amount":1,"per":"Life","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Wizard', 71, 3, 1, null, '{"amount":1,"per":"Refresh","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Wizard', 79, 3, 1, null, '{"amount":1,"per":"Life","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Wizard', 82, 3, 1, 3, '{"amount":1,"per":"Ball","charge":"Unlimited"}'::jsonb, false, 'level_spell', null, false),
  ('Wizard', 92, 3, 1, 4, '{"amount":1,"per":"Ball","charge":"Unlimited"}'::jsonb, false, 'level_spell', null, false),
  ('Wizard', 122, 3, 1, null, '{"amount":2,"per":"Life","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Wizard', 138, 3, 1, null, '{"amount":1,"per":"Refresh","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Wizard', 162, 3, 1, null, '{"amount":1,"per":"Refresh","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Wizard', 41, 4, 1, null, '{"amount":2,"per":"Refresh","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Wizard', 38, 4, 1, null, '{"amount":1,"per":"Refresh","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Wizard', 60, 4, 1, 4, '{"amount":1,"per":"Ball","charge":"Unlimited"}'::jsonb, false, 'level_spell', null, false),
  ('Wizard', 83, 4, 1, null, '{"amount":1,"per":"Refresh","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Wizard', 133, 4, 1, null, '{"amount":1,"per":"Refresh","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Wizard', 156, 4, 1, null, '{"amount":1,"per":"Refresh","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Wizard', 159, 4, 1, 2, '{"amount":1,"per":"Life","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Wizard', 168, 4, 1, null, '{"amount":1,"per":"Refresh","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Wizard', 174, 4, 1, null, '{"amount":1,"per":"Refresh","charge":"Charge x3"}'::jsonb, false, 'level_spell', null, false),
  ('Wizard', 6, 5, 1, 2, '{"amount":1,"per":"Life","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Wizard', 34, 5, 1, null, '{"amount":1,"per":"Refresh","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Wizard', 175, 5, 4, 1, null, false, 'level_spell', null, false),
  ('Wizard', 107, 5, 1, 4, '{"amount":1,"per":"Ball","charge":"Unlimited"}'::jsonb, false, 'level_spell', null, false),
  ('Wizard', 115, 5, 1, 2, '{"amount":1,"per":"Refresh","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Wizard', 151, 5, 1, 2, '{"amount":1,"per":"Life","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Wizard', 169, 5, 1, 2, '{"amount":1,"per":"Refresh","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Wizard', 170, 5, 1, 2, '{"amount":1,"per":"Refresh","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Wizard', 18, 6, 2, 1, null, false, 'level_spell', null, false),
  ('Wizard', 45, 6, 1, 2, '{"amount":1,"per":"Refresh","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Wizard', 54, 6, 2, 1, null, false, 'level_spell', null, false),
  ('Wizard', 59, 6, 1, null, '{"amount":1,"per":"Refresh","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Wizard', 105, 6, 2, null, '{"amount":1,"per":"Refresh","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Wizard', 118, 6, 1, null, '{"amount":1,"per":"Refresh","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Wizard', 149, 6, 2, 1, '{"amount":1,"per":"Ball","charge":"Unlimited"}'::jsonb, false, 'level_spell', null, false),
  ('Wizard', 172, 6, 2, 1, null, false, 'level_spell', null, false),
  ('Wizard', 173, 6, 1, null, '{"amount":1,"per":"Refresh","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Druid', 14, 1, 1, 2, '{"amount":1,"per":"Refresh","charge":"Charge x10"}'::jsonb, false, 'level_spell', null, false),
  ('Druid', 48, 1, 1, 2, '{"amount":2,"per":"Balls","charge":"Unlimited"}'::jsonb, false, 'level_spell', null, false),
  ('Druid', 52, 1, 2, 2, null, false, 'level_spell', null, false),
  ('Druid', 56, 1, 2, 2, null, false, 'level_spell', null, false),
  ('Druid', 78, 1, 1, null, '{"amount":1,"per":"Life","charge":"Charge x3"}'::jsonb, false, 'level_spell', null, false),
  ('Druid', 84, 1, 1, null, '{"amount":1,"per":"Life","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Druid', 98, 1, 1, null, '{"amount":1,"per":"Life","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Druid', 35, 2, 1, 1, '{"amount":1,"per":"Refresh","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Druid', 51, 2, 4, 1, null, false, 'level_spell', null, false),
  ('Druid', 61, 2, 1, 2, '{"amount":2,"per":"Balls","charge":"Unlimited"}'::jsonb, false, 'level_spell', null, false),
  ('Druid', 63, 2, 1, 2, '{"amount":1,"per":"Refresh","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Druid', 75, 2, 1, null, '{"amount":1,"per":"Life","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Druid', 86, 2, 1, 4, '{"amount":1,"per":"Refresh","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Druid', 111, 2, 1, null, '{"amount":1,"per":"Life","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Druid', 124, 2, 1, null, '{"amount":1,"per":"Life","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Druid', 152, 2, 1, null, '{"amount":1,"per":"Refresh","charge":"Charge x3"}'::jsonb, false, 'level_spell', null, false),
  ('Druid', 17, 3, 1, 2, '{"amount":1,"per":"Refresh","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Druid', 179, 3, 1, null, '{"amount":1,"per":"Refresh","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Druid', 43, 3, 1, null, '{"amount":1,"per":"Refresh","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Druid', 58, 3, 1, 2, '{"amount":1,"per":"Life","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Druid', 64, 3, 1, 2, '{"amount":1,"per":"Refresh","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Druid', 71, 3, 1, null, '{"amount":1,"per":"Refresh","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Druid', 83, 3, 1, 2, '{"amount":1,"per":"Life","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Druid', 123, 3, 1, null, '{"amount":1,"per":"Refresh","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Druid', 153, 3, 1, 2, '{"amount":1,"per":"Refresh","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Druid', 175, 4, 4, 1, null, false, 'level_spell', null, false),
  ('Druid', 65, 4, 2, 2, '{"amount":1,"per":"Refresh","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Druid', 67, 4, 1, 2, '{"amount":1,"per":"Refresh","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Druid', 68, 4, 1, null, '{"amount":1,"per":"Refresh","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Druid', 82, 4, 1, 2, '{"amount":1,"per":"Ball","charge":"Unlimited"}'::jsonb, false, 'level_spell', null, false),
  ('Druid', 94, 4, 1, 2, '{"amount":1,"per":"Refresh","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Druid', 159, 4, 1, 2, '{"amount":1,"per":"Life","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Druid', 160, 4, 1, 2, '{"amount":1,"per":"Life","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Druid', 6, 5, 1, 2, '{"amount":1,"per":"Life","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Druid', 177, 5, 5, 1, null, false, 'level_spell', null, false),
  ('Druid', 53, 5, 1, null, '{"amount":1,"per":"Refresh","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Druid', 62, 5, 1, 2, '{"amount":1,"per":"Refresh","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Druid', 77, 5, 1, 2, '{"amount":1,"per":"Refresh","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Druid', 89, 5, 1, 2, '{"amount":1,"per":"Refresh","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Druid', 113, 5, 1, 2, '{"amount":1,"per":"Refresh","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Druid', 127, 5, 2, null, '{"amount":1,"per":"Refresh","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Druid', 165, 5, 1, 2, '{"amount":1,"per":"Refresh","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Druid', 19, 6, 1, 1, null, false, 'level_spell', null, false),
  ('Druid', 24, 6, 1, null, '{"amount":1,"per":"Refresh","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Druid', 180, 6, 1, null, '{"amount":1,"per":"Refresh","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Druid', 103, 6, 1, 2, '{"amount":1,"per":"Refresh","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Druid', 121, 6, 2, 1, null, false, 'level_spell', null, false),
  ('Druid', 137, 6, 1, 1, '{"amount":1,"per":"Refresh","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Druid', 155, 6, 2, 1, null, false, 'level_spell', null, false),
  ('Druid', 173, 6, 1, null, '{"amount":1,"per":"Refresh","charge":null}'::jsonb, false, 'level_spell', null, false),
  ('Anti-Paladin', 182, 1, 0, null, '{"amount":null,"per":null,"charge":null}'::jsonb, false, 'base', null, false),
  ('Anti-Paladin', 183, 1, 0, null, '{"amount":null,"per":null,"charge":null}'::jsonb, false, 'base', null, false),
  ('Anti-Paladin', 111, 2, 0, null, '{"amount":1,"per":"Life","charge":"Charge x3"}'::jsonb, false, 'base', null, false),
  ('Anti-Paladin', 151, 3, 0, null, '{"amount":1,"per":"Life","charge":"Charge x5"}'::jsonb, false, 'base', null, false),
  ('Anti-Paladin', 32, 4, 0, null, '{"amount":1,"per":"Life","charge":"Charge x10"}'::jsonb, false, 'base', null, false),
  ('Anti-Paladin', 161, 5, 0, null, '{"amount":1,"per":"Life","charge":null}'::jsonb, false, 'base', null, false),
  ('Anti-Paladin', 189, 6, 0, null, '{"amount":2,"per":"Refresh","charge":null}'::jsonb, false, 'base', null, false),
  ('Anti-Paladin', 85, 6, 0, null, '{"amount":null,"per":null,"charge":null}'::jsonb, false, 'optional_pick_one', null, false),
  ('Anti-Paladin', 36, 6, 0, null, '{"amount":null,"per":null,"charge":null}'::jsonb, false, 'optional_pick_one', null, false),
  ('Anti-Paladin', 161, 1, 0, null, '{"amount":1,"per":"Life","charge":null}'::jsonb, false, 'look_the_part', null, true),
  ('Archer', 125, 1, 0, null, '{"amount":1,"per":"Refresh","charge":"Charge x3"}'::jsonb, false, 'base', null, false),
  ('Archer', 37, 1, 0, null, '{"amount":1,"per":"Arrow","charge":"Unlimited"}'::jsonb, false, 'pick_two_of_three', null, false),
  ('Archer', 109, 1, 0, null, '{"amount":1,"per":"Arrow","charge":"Unlimited"}'::jsonb, false, 'pick_two_of_three', null, false),
  ('Archer', 112, 1, 0, null, '{"amount":1,"per":"Arrow","charge":"Unlimited"}'::jsonb, false, 'pick_two_of_three', null, false),
  ('Archer', 98, 2, 0, null, '{"amount":1,"per":"Life","charge":"Charge x5"}'::jsonb, false, 'base', null, false),
  ('Archer', 37, 3, 0, null, '{"amount":1,"per":"Arrow","charge":"Unlimited"}'::jsonb, false, 'pick_two_of_three', null, false),
  ('Archer', 109, 3, 0, null, '{"amount":1,"per":"Arrow","charge":"Unlimited"}'::jsonb, false, 'pick_two_of_three', null, false),
  ('Archer', 112, 3, 0, null, '{"amount":1,"per":"Arrow","charge":"Unlimited"}'::jsonb, false, 'pick_two_of_three', null, false),
  ('Archer', 157, 4, 0, null, '{"amount":1,"per":"Arrow","charge":"Unlimited"}'::jsonb, false, 'base', null, false),
  ('Archer', 37, 5, 0, null, '{"amount":1,"per":"Arrow","charge":"Unlimited"}'::jsonb, false, 'pick_two_of_three', null, false),
  ('Archer', 109, 5, 0, null, '{"amount":1,"per":"Arrow","charge":"Unlimited"}'::jsonb, false, 'pick_two_of_three', null, false),
  ('Archer', 112, 5, 0, null, '{"amount":1,"per":"Arrow","charge":"Unlimited"}'::jsonb, false, 'pick_two_of_three', null, false),
  ('Archer', 106, 6, 0, null, '{"amount":1,"per":"Arrow","charge":"Unlimited"}'::jsonb, false, 'base', null, false),
  ('Archer', 139, 6, 0, null, '{"amount":null,"per":null,"charge":null}'::jsonb, false, 'optional_pick_one', null, false),
  ('Archer', 10, 6, 0, null, '{"amount":null,"per":null,"charge":null}'::jsonb, false, 'optional_pick_one', null, false),
  ('Archer', 37, 1, 0, null, '{"amount":1,"per":"Arrow","charge":"Unlimited"}'::jsonb, false, 'look_the_part', null, true),
  ('Archer', 109, 1, 0, null, '{"amount":1,"per":"Arrow","charge":"Unlimited"}'::jsonb, false, 'look_the_part', null, true),
  ('Archer', 112, 1, 0, null, '{"amount":1,"per":"Arrow","charge":"Unlimited"}'::jsonb, false, 'look_the_part', null, true),
  ('Assassin', 191, 1, 0, null, '{"amount":null,"per":null,"charge":null}'::jsonb, false, 'base', null, false),
  ('Assassin', 11, 1, 0, null, '{"amount":null,"per":null,"charge":"Unlimited"}'::jsonb, false, 'base', null, false),
  ('Assassin', 131, 1, 0, null, '{"amount":2,"per":"Life","charge":null}'::jsonb, false, 'base', null, false),
  ('Assassin', 111, 2, 0, null, '{"amount":1,"per":"Life","charge":"Charge x3"}'::jsonb, false, 'pick_one', null, false),
  ('Assassin', 112, 2, 0, null, '{"amount":2,"per":"Arrows","charge":"Unlimited"}'::jsonb, false, 'pick_one', null, false),
  ('Assassin', 27, 3, 0, null, '{"amount":2,"per":"Life","charge":null}'::jsonb, false, 'base', null, false),
  ('Assassin', 79, 4, 0, null, '{"amount":1,"per":"Life","charge":null}'::jsonb, false, 'base', null, false),
  ('Assassin', 190, 5, 0, null, '{"amount":2,"per":"Life","charge":null}'::jsonb, false, 'base', null, false),
  ('Assassin', 39, 6, 0, null, '{"amount":1,"per":"Life","charge":null}'::jsonb, false, 'base', null, false),
  ('Assassin', 181, 6, 0, null, '{"amount":null,"per":null,"charge":null}'::jsonb, false, 'optional_pick_one', null, false),
  ('Assassin', 150, 6, 0, null, '{"amount":null,"per":null,"charge":null}'::jsonb, false, 'optional_pick_one', null, false),
  ('Assassin', 111, 1, 0, null, '{"amount":1,"per":"Life","charge":"Charge x3"}'::jsonb, false, 'look_the_part', null, true),
  ('Assassin', 201, 1, 0, null, '{"amount":1,"per":"Arrow","charge":"Unlimited"}'::jsonb, false, 'look_the_part', null, true),
  ('Barbarian', 192, 1, 0, null, '{"amount":null,"per":null,"charge":null}'::jsonb, false, 'base', null, false),
  ('Barbarian', 182, 1, 0, null, '{"amount":null,"per":null,"charge":null}'::jsonb, false, 'base', null, false),
  ('Barbarian', 184, 1, 0, null, '{"amount":null,"per":null,"charge":null}'::jsonb, false, 'base', null, false),
  ('Barbarian', 116, 2, 0, null, '{"amount":1,"per":"Refresh","charge":"Charge x10"}'::jsonb, false, 'base', null, false),
  ('Barbarian', 4, 3, 0, null, '{"amount":null,"per":null,"charge":"Unlimited"}'::jsonb, false, 'base', null, false),
  ('Barbarian', 116, 4, 0, null, '{"amount":1,"per":"Refresh","charge":"Charge x10"}'::jsonb, false, 'base', null, false),
  ('Barbarian', 32, 5, 0, null, '{"amount":1,"per":"Life","charge":"Charge x3"}'::jsonb, false, 'base', null, false),
  ('Barbarian', 30, 6, 0, null, '{"amount":null,"per":null,"charge":"Unlimited"}'::jsonb, false, 'base', null, false),
  ('Barbarian', 117, 6, 0, null, '{"amount":null,"per":null,"charge":null}'::jsonb, false, 'optional_pick_one', null, false),
  ('Barbarian', 22, 6, 0, null, '{"amount":null,"per":null,"charge":null}'::jsonb, false, 'optional_pick_one', null, false),
  ('Barbarian', 116, 1, 0, null, '{"amount":1,"per":"Refresh","charge":"Charge x10"}'::jsonb, false, 'look_the_part', null, true),
  ('Monk', 193, 1, 0, null, '{"amount":null,"per":null,"charge":null}'::jsonb, false, 'base', null, false),
  ('Monk', 194, 1, 0, null, '{"amount":null,"per":null,"charge":null}'::jsonb, false, 'base', null, false),
  ('Monk', 13, 2, 0, null, '{"amount":1,"per":"Life","charge":"Charge x5"}'::jsonb, false, 'base', null, false),
  ('Monk', 128, 3, 0, null, '{"amount":1,"per":"Life","charge":"Charge x5"}'::jsonb, false, 'base', null, false),
  ('Monk', 75, 4, 0, null, '{"amount":1,"per":"Life","charge":"Charge x3"}'::jsonb, false, 'base', null, false),
  ('Monk', 127, 5, 0, null, '{"amount":1,"per":"Refresh","charge":"Charge x5"}'::jsonb, false, 'base', null, false),
  ('Monk', 86, 6, 0, null, '{"amount":1,"per":"Life","charge":null}'::jsonb, false, 'base', null, false),
  ('Monk', 97, 6, 0, null, '{"amount":null,"per":null,"charge":null}'::jsonb, false, 'optional_pick_one', null, false),
  ('Monk', 102, 6, 0, null, '{"amount":null,"per":null,"charge":null}'::jsonb, false, 'optional_pick_one', null, false),
  ('Monk', 75, 1, 0, null, '{"amount":1,"per":"Life","charge":null}'::jsonb, false, 'look_the_part', null, true),
  ('Paladin', 182, 1, 0, null, '{"amount":null,"per":null,"charge":null}'::jsonb, false, 'base', null, false),
  ('Paladin', 185, 1, 0, null, '{"amount":null,"per":null,"charge":null}'::jsonb, false, 'base', null, false),
  ('Paladin', 70, 2, 0, null, '{"amount":1,"per":"Life","charge":"Charge x3"}'::jsonb, false, 'base', null, false),
  ('Paladin', 57, 3, 0, null, '{"amount":1,"per":"Refresh","charge":"Charge x5"}'::jsonb, false, 'base', null, false),
  ('Paladin', 72, 4, 0, null, '{"amount":1,"per":"Life","charge":null}'::jsonb, false, 'base', null, false),
  ('Paladin', 20, 5, 0, null, '{"amount":1,"per":"Life","charge":null}'::jsonb, false, 'base', null, false),
  ('Paladin', 195, 6, 0, null, '{"amount":2,"per":"Refresh","charge":null}'::jsonb, false, 'base', null, false),
  ('Paladin', 73, 6, 0, null, '{"amount":null,"per":null,"charge":null}'::jsonb, false, 'optional_pick_one', null, false),
  ('Paladin', 87, 6, 0, null, '{"amount":null,"per":null,"charge":null}'::jsonb, false, 'optional_pick_one', null, false),
  ('Paladin', 20, 1, 0, null, '{"amount":1,"per":"Life","charge":null}'::jsonb, false, 'look_the_part', null, true),
  ('Scout', 163, 1, 0, null, '{"amount":2,"per":"Life","charge":"Charge x3"}'::jsonb, false, 'base', null, false),
  ('Scout', 75, 2, 0, null, '{"amount":1,"per":"Life","charge":null}'::jsonb, false, 'base', null, false),
  ('Scout', 124, 2, 0, null, '{"amount":1,"per":"Life","charge":"Charge x3"}'::jsonb, false, 'base', null, false),
  ('Scout', 43, 3, 0, null, '{"amount":1,"per":"Refresh","charge":"Charge x5"}'::jsonb, false, 'base', null, false),
  ('Scout', 131, 3, 0, null, '{"amount":1,"per":"Life","charge":null}'::jsonb, false, 'base', null, false),
  ('Scout', 79, 4, 0, null, '{"amount":1,"per":"Life","charge":null}'::jsonb, false, 'pick_one', null, false),
  ('Scout', 109, 4, 0, null, '{"amount":1,"per":"Arrow","charge":"Unlimited"}'::jsonb, false, 'pick_one', null, false),
  ('Scout', 196, 5, 0, null, '{"amount":null,"per":null,"charge":null}'::jsonb, false, 'base', null, false),
  ('Scout', 197, 6, 0, null, '{"amount":1,"per":"Life","charge":null}'::jsonb, false, 'base', null, false),
  ('Scout', 80, 6, 0, null, '{"amount":null,"per":null,"charge":null}'::jsonb, false, 'optional_pick_one', null, false),
  ('Scout', 79, 6, 0, null, '{"amount":1,"per":"Life","charge":"Charge x3"}'::jsonb, false, 'optional_pick_one_nested_pickOne', '80:pickOne', false),
  ('Scout', 109, 6, 0, null, '{"amount":2,"per":"Arrows","charge":"Unlimited"}'::jsonb, false, 'optional_pick_one_nested_pickOne', '80:pickOne', false),
  ('Scout', 9, 6, 0, null, '{"amount":null,"per":null,"charge":null}'::jsonb, false, 'optional_pick_one', null, false),
  ('Scout', 75, 1, 0, null, '{"amount":1,"per":"Life","charge":null}'::jsonb, false, 'look_the_part', null, true),
  ('Warrior', 198, 1, 0, null, '{"amount":1,"per":"Life","charge":null}'::jsonb, false, 'base', null, false),
  ('Warrior', 129, 2, 0, null, '{"amount":null,"per":null,"charge":"Unlimited"}'::jsonb, false, 'base', null, false),
  ('Warrior', 166, 3, 0, null, '{"amount":2,"per":"Refresh","charge":null}'::jsonb, false, 'base', null, false),
  ('Warrior', 88, 4, 0, null, '{"amount":1,"per":"Life","charge":null}'::jsonb, false, 'base', null, false),
  ('Warrior', 132, 5, 0, null, '{"amount":1,"per":"Refresh","charge":"Charge x3"}'::jsonb, false, 'base', null, false),
  ('Warrior', 188, 6, 0, null, '{"amount":3,"per":"Refresh","charge":"Charge x10"}'::jsonb, false, 'base', null, false),
  ('Warrior', 178, 6, 0, null, '{"amount":null,"per":null,"charge":null}'::jsonb, false, 'optional_pick_one', null, false),
  ('Warrior', 90, 6, 0, null, '{"amount":null,"per":null,"charge":null}'::jsonb, false, 'optional_pick_one', null, false),
  ('Warrior', 88, 1, 0, null, '{"amount":1,"per":"Life","charge":null}'::jsonb, false, 'look_the_part', null, true)
on conflict do nothing;
